#ifndef BETHKIT_H
#define BETHKIT_H

/* Auto-generated by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Current major C ABI version.
 */
#define BETHKIT_ABI_VERSION 2

/**
 * BSA archive format version.
 */
typedef enum BethkitBsaVersion {
    /**
     * TES III Morrowind BSA (version 0x100).
     */
    Tes3 = 0,
    /**
     * TES IV Oblivion BSA (version 0x67).
     */
    Tes4 = 1,
    /**
     * Fallout 3 / New Vegas BSA (version 0x68).
     */
    Fo3 = 2,
    /**
     * Skyrim / Skyrim SE BSA (version 0x69).
     */
    Sse = 3,
} BethkitBsaVersion;

/**
 * BA2 archive format version.
 */
typedef enum BethkitBa2Version {
    /**
     * Fallout 4 BA2 (version 1).
     */
    V1 = 0,
    /**
     * Fallout 4 Next-Gen BA2 (version 7).
     */
    V7 = 1,
    /**
     * Fallout 4 Next-Gen BA2 (version 8).
     */
    V8 = 2,
} BethkitBa2Version;

/**
 * Plugin file type (determines FormID space and load-order slot allocation).
 */
typedef enum BethkitPluginKind {
    /**
     * Full ESP/ESM plugin (up to 0xFFFFFE records, index occupies one master slot).
     */
    Full = 0,
    /**
     * Light ESL plugin (up to 0xFFF records in the 0xFE00–0xFEFF range).
     */
    Light = 1,
    /**
     * Overlay plugin (Starfield+; shares space with the plugin it overrides).
     */
    Overlay = 2,
} BethkitPluginKind;

/**
 * Bethesda game target for plugin and archive operations.
 */
typedef enum BethkitGame {
    /**
     * The Elder Scrolls V: Skyrim (original 2011 release).
     */
    SkyrimLe = 0,
    /**
     * The Elder Scrolls V: Skyrim Special Edition (and Anniversary Edition).
     */
    SkyrimSe = 1,
    /**
     * The Elder Scrolls V: Skyrim VR.
     */
    SkyrimVr = 2,
    /**
     * Fallout 3.
     */
    Fallout3 = 3,
    /**
     * Fallout: New Vegas.
     */
    FalloutNv = 4,
    /**
     * Fallout 4.
     */
    Fallout4 = 5,
    /**
     * Fallout 4 VR.
     */
    Fallout4Vr = 6,
    /**
     * Fallout 76.
     */
    Fallout76 = 7,
    /**
     * The Elder Scrolls IV: Oblivion.
     */
    Oblivion = 8,
    /**
     * The Elder Scrolls III: Morrowind.
     */
    Morrowind = 9,
    /**
     * Starfield.
     */
    Starfield = 10,
} BethkitGame;

/**
 * Discriminant for [`BethkitFieldValuePayload`], identifying which union arm
 * is active in a [`BethkitFieldValue`].
 */
typedef enum BethkitFieldValueKind {
    /**
     * A signed integer value (i64); covers Int8 through Int32 and UInt8 through UInt32.
     */
    Int = 0,
    /**
     * A floating-point value (f64); covers Float32.
     */
    Float = 1,
    /**
     * A NUL-terminated inline string borrowed from the record data.
     */
    Str = 2,
    /**
     * An untyped FormID (u32).
     */
    FormId = 3,
    /**
     * A typed FormID with a set of allowed target record signatures.
     */
    FormIdTyped = 4,
    /**
     * Raw bytes borrowed from the record data.
     */
    Bytes = 5,
    /**
     * An enumeration value with an optional resolved name.
     */
    Enum = 6,
    /**
     * A set of named bit flags.
     */
    Flags = 7,
    /**
     * A fixed-layout struct decoded into named sub-fields.
     */
    Struct = 8,
    /**
     * A homogeneous array of field values.
     */
    Array = 9,
    /**
     * The subrecord matching this field definition was absent from the record.
     */
    Missing = 10,
    /**
     * An unsigned 64-bit integer that cannot be losslessly represented as i64.
     */
    UInt = 11,
} BethkitFieldValueKind;

/**
 * Identifies one of the three localized string table file types.
 */
typedef enum BethkitStringFileKind {
    /**
     * `.strings` — null-terminated inline strings.
     */
    Strings = 0,
    /**
     * `.dlstrings` — length-prefixed strings (dialogue lines).
     */
    DlStrings = 1,
    /**
     * `.ilstrings` — length-prefixed strings (info lines).
     */
    IlStrings = 2,
} BethkitStringFileKind;

/**
 * An opaque handle to an opened BSA or BA2 archive.
 *
 * Created by [`bethkit_archive_open`].  Must be freed with
 * [`bethkit_archive_free`].
 */
typedef struct BethkitArchive BethkitArchive;

/**
 * An opaque handle to a BA2 DX10 (texture) archive writer.
 *
 * Created by [`bethkit_ba2_dx10_writer_new`].  Must be freed with
 * [`bethkit_ba2_dx10_writer_free`].
 */
typedef struct BethkitBa2Dx10Writer BethkitBa2Dx10Writer;

/**
 * An opaque handle to a BA2 general-content archive writer.
 *
 * Created by [`bethkit_ba2_gnrl_writer_new`].  Must be freed with
 * [`bethkit_ba2_gnrl_writer_free`].
 */
typedef struct BethkitBa2GnrlWriter BethkitBa2GnrlWriter;

/**
 * An opaque handle to a BSA archive writer.
 *
 * Created by [`bethkit_bsa_writer_new`].  Must be freed with
 * [`bethkit_bsa_writer_free`].  After calling [`bethkit_bsa_writer_write_to`]
 * the writer is consumed; further calls to `write_to` return -1.
 */
typedef struct BethkitBsaWriter BethkitBsaWriter;

/**
 * A heap-allocated list of named fields decoded from a struct field.
 *
 * Ownership depends on how this was obtained:
 * - **Detached** (returned directly to the caller): free with
 *   [`bethkit_field_entries_free`].
 * - **Embedded in a [`BethkitRecordView`]**: freed automatically by
 *   [`bethkit_record_view_free`] — **do not** call [`bethkit_field_entries_free`]
 *   on it or a double-free will occur.
 */
typedef struct BethkitFieldEntries BethkitFieldEntries;

/**
 * A heap-allocated list of field values decoded from an array field.
 *
 * Ownership depends on how this was obtained:
 * - **Detached** (returned directly to the caller): free with
 *   [`bethkit_field_values_free`].
 * - **Embedded in a [`BethkitRecordView`]**: freed automatically by
 *   [`bethkit_record_view_free`] — **do not** call [`bethkit_field_values_free`]
 *   on it or a double-free will occur.
 */
typedef struct BethkitFieldValues BethkitFieldValues;

/**
 * An opaque handle to an ordered list of plugin files.
 *
 * Created by [`bethkit_load_order_new`].  Must be freed with
 * [`bethkit_load_order_free`].
 */
typedef struct BethkitLoadOrder BethkitLoadOrder;

/**
 * An opaque handle to a localization set (the three sibling string tables
 * `.strings`, `.dlstrings`, and `.ilstrings` for one plugin + language).
 *
 * Created by [`bethkit_localization_set_new`] or
 * [`bethkit_localization_set_open`].  Must be freed with
 * [`bethkit_localization_set_free`].
 */
typedef struct BethkitLocalizationSet BethkitLocalizationSet;

/**
 * An opaque handle to an opened Bethesda plugin file.
 *
 * Created by [`bethkit_plugin_open`] or [`bethkit_plugin_open_from_bytes`].
 * Must be freed with [`bethkit_plugin_free`].
 */
typedef struct BethkitPlugin BethkitPlugin;

/**
 * An opaque handle to a multi-plugin record cache.
 *
 * Created by [`bethkit_plugin_cache_new`].  Must be freed with
 * [`bethkit_plugin_cache_free`].
 */
typedef struct BethkitPluginCache BethkitPluginCache;

/**
 * An owned patch session whose source bytes outlive the original plugin handle.
 *
 * Release with [`bethkit_plugin_patcher_free`]. Replacements are copied and do
 * not consume their writable record handles. Unchanged records remain verbatim.
 */
typedef struct BethkitPluginPatcher BethkitPluginPatcher;

/**
 * An opaque handle to a plugin writer.
 *
 * Created by [`bethkit_plugin_writer_new`].  Must be freed with
 * [`bethkit_plugin_writer_free`].
 */
typedef struct BethkitPluginWriter BethkitPluginWriter;

/**
 * Owned lossless semantic record editor.
 */
typedef struct BethkitRecordEditor BethkitRecordEditor;

/**
 * An owned, schema-guided snapshot of all decoded fields from a record.
 *
 * Created by [`bethkit_record_view_new`].  Must be freed with
 * [`bethkit_record_view_free`].
 */
typedef struct BethkitRecordView BethkitRecordView;

/**
 * Owned catalog of schema packages.
 */
typedef struct BethkitSchemaCatalog BethkitSchemaCatalog;

/**
 * Owned schema-package handle.
 */
typedef struct BethkitSchemaPackage BethkitSchemaPackage;

/**
 * Owned semantic runtime context.
 */
typedef struct BethkitSemanticContext BethkitSemanticContext;

/**
 * An opaque handle to a single string table (`.strings`, `.dlstrings`, or
 * `.ilstrings`).
 *
 * Created by [`bethkit_string_table_new`] or [`bethkit_string_table_open`].
 * Must be freed with [`bethkit_string_table_free`].
 */
typedef struct BethkitStringTable BethkitStringTable;

/**
 * An opaque handle to a writable top-level group.
 *
 * Created by [`bethkit_writable_group_new`].  Ownership is transferred to
 * the plugin writer or a parent group when passed to the respective
 * `add_group` function.
 */
typedef struct BethkitWritableGroup BethkitWritableGroup;

/**
 * An opaque handle to a writable record.
 *
 * Created by [`bethkit_writable_record_new`].  Ownership is transferred to
 * the parent group when passed to [`bethkit_writable_group_add_record`].
 */
typedef struct BethkitWritableRecord BethkitWritableRecord;

/**
 * A borrowed, read-only handle to an archive entry.
 *
 * Obtained from [`bethkit_archive_entry_get`].  Valid for the lifetime of
 * the owning [`BethkitArchive`].  Never free this handle.
 */
typedef ArchiveEntry BethkitArchiveEntry;

/**
 * A borrowed, read-only handle to a plugin record.
 *
 * The pointer is valid for the lifetime of the `BethkitPlugin` it was
 * obtained from.  Never free this handle.
 */
typedef Record BethkitRecord;

/**
 * A globally unique FormID, combining the source plugin name and a
 * 24-bit object ID.
 */
typedef struct BethkitGlobalFormId {
    /**
     * NUL-terminated plugin file name.  Borrowed from the owning
     * [`BethkitLoadOrder`] or [`BethkitPluginCache`]; valid until that
     * object is freed.
     */
    const char *plugin_name;
    /**
     * The 24-bit object ID component of the global FormID.
     */
    uint32_t object_id;
} BethkitGlobalFormId;

/**
 * A borrowed, read-only handle to a record group.
 *
 * Obtained from [`bethkit_plugin_group_get`] or
 * [`bethkit_group_child_as_group`].  Valid for the lifetime of the owning
 * `BethkitPlugin`.  Never free this handle.
 */
typedef Group BethkitGroup;

/**
 * A borrowed, read-only handle to a subrecord within a [`BethkitRecord`].
 *
 * The pointer is valid for the lifetime of the `BethkitPlugin` it was
 * obtained from.  Never free this handle.
 */
typedef SubRecord BethkitSubRecord;

/**
 * A non-owning view of a byte slice passed across the FFI boundary.
 *
 * `ptr` points into memory owned by the object that produced this slice;
 * the slice is valid as long as the owning object is alive.
 */
typedef struct BethkitSlice {
    /**
     * Pointer to the first byte of the slice.
     */
    const uint8_t *ptr;
    /**
     * Number of bytes in the slice.
     */
    uintptr_t len;
} BethkitSlice;

/**
 * A typed FormID with its allowed target record-type signatures.
 *
 * `allowed_sigs` points to an array of 4-byte signatures; the slice is
 * `allowed_count` entries long. The owning record view retains the array
 * until that view is freed. Never free it separately.
 */
typedef struct BethkitTypedFormId {
    /**
     * The raw file-local FormID value.
     */
    uint32_t raw;
    /**
     * Pointer to the first element of the allowed-signatures array.
     */
    const uint8_t (*allowed_sigs)[4];
    /**
     * Number of entries in `allowed_sigs`.
     */
    uintptr_t allowed_count;
} BethkitTypedFormId;

/**
 * An enumeration field value with its raw integer and optional resolved name.
 *
 * `name` is null when the raw value does not correspond to any known variant
 * in the schema.  When non-null it points into the owning view's string
 * arena and is valid until the view is freed; never free this pointer.
 */
typedef struct BethkitEnumVal {
    /**
     * The raw integer value from the record.
     */
    int64_t value;
    /**
     * Name of the enum variant, or null if unknown.
     */
    const char *name;
} BethkitEnumVal;

/**
 * A flags field value with the raw integer and the names of all active bits.
 *
 * `active_names` points to an array of `active_count` NUL-terminated C-string
 * pointers.  The *array itself* is heap-allocated and is freed when the
 * enclosing [`BethkitFieldValue`] is released (via the view or entry free
 * functions).  The individual string pointers are interned in the owning
 * view's string arena and are valid until that view is freed.  Do not free
 * the individual string pointers.
 */
typedef struct BethkitFlagsVal {
    /**
     * The raw integer value from the record.
     */
    uint64_t raw_value;
    /**
     * Pointer to the first element of the active-names pointer array.
     */
    const char *const *active_names;
    /**
     * Number of entries in `active_names`.
     */
    uintptr_t active_count;
} BethkitFlagsVal;

/**
 * The payload union inside [`BethkitFieldValue`].
 *
 * Only the arm corresponding to [`BethkitFieldValue::kind`] is valid.
 */
typedef union BethkitFieldValuePayload {
    /**
     * Active when `kind == Int`.
     */
    int64_t int_val;
    /**
     * Active when `kind == UInt`.
     */
    uint64_t uint_val;
    /**
     * Active when `kind == Float`.
     */
    double float_val;
    /**
     * Active when `kind == Str`.  Borrowed from the owning view.
     */
    const char *str_val;
    /**
     * Active when `kind == FormId`.
     */
    uint32_t form_id;
    /**
     * Active when `kind == FormIdTyped`.
     */
    struct BethkitTypedFormId form_id_typed;
    /**
     * Active when `kind == Bytes`.  Borrowed from the owning view.
     */
    struct BethkitSlice bytes;
    /**
     * Active when `kind == Enum`.
     */
    struct BethkitEnumVal enum_val;
    /**
     * Active when `kind == Flags`.  The flags value owns its active-names
     * array and is dropped when the enclosing [`BethkitNamedField`] is freed.
     */
    struct BethkitFlagsVal flags_val;
    /**
     * Active when `kind == Struct`.  Owned by the enclosing
     * [`BethkitRecordView`]; recursively freed by [`bethkit_record_view_free`].
     * **Do not pass to [`bethkit_field_entries_free`] if this value was
     * obtained from a view** — that causes a double-free.
     */
    struct BethkitFieldEntries *struct_entries;
    /**
     * Active when `kind == Array`.  Owned by the enclosing
     * [`BethkitRecordView`]; recursively freed by [`bethkit_record_view_free`].
     * **Do not pass to [`bethkit_field_values_free`] if this value was
     * obtained from a view** — that causes a double-free.
     */
    struct BethkitFieldValues *array_values;
    /**
     * Active when `kind == Missing` or `kind == FormId` with zero value.
     * No meaningful data; present so the union is never zero-sized.
     */
    uint64_t _pad;
} BethkitFieldValuePayload;

/**
 * A decoded field value stored as a `#[repr(C)]` tagged union.
 *
 * Inspect `kind` to determine which arm of `payload` is active.  Arms that
 * allocate heap memory (`Struct`, `Array`, `Flags`) must be released with
 * the appropriate free functions when the containing [`BethkitRecordView`]
 * is freed (this is done automatically by [`bethkit_record_view_free`]).
 * Do not release fields borrowed from a view after the view has been freed.
 */
typedef struct BethkitFieldValue {
    /**
     * Identifies the active arm of `payload`.
     */
    enum BethkitFieldValueKind kind;
    /**
     * The decoded value payload.
     */
    union BethkitFieldValuePayload payload;
} BethkitFieldValue;

/**
 * A named field snapshot inside a [`BethkitRecordView`] or
 * [`BethkitFieldEntries`].
 */
typedef struct BethkitNamedField {
    /**
     * Human-readable field name from the schema.  Points into the owning
     * view's string arena; valid until the view is freed.  Never free this
     * pointer directly.
     */
    const char *name;
    /**
     * The decoded field value.
     */
    struct BethkitFieldValue value;
} BethkitNamedField;

/**
 * Stable identity and byte provenance for a decoded field.
 *
 * String pointers are borrowed from the owning view and expire when it is freed.
 * The layout of [`BethkitNamedField`] remains unchanged; retrieve this metadata
 * with [`bethkit_record_view_field_metadata`] or [`bethkit_field_entries_metadata`].
 */
typedef struct BethkitFieldMetadata {
    /**
     * Stable schema node identifier, or `UINT32_MAX` for an unknown subrecord.
     */
    uint32_t node_id;
    /**
     * Stable schema path, borrowed from the owning view.
     */
    const char *path;
    /**
     * Selected union-node path, or null when no alternative path applies.
     */
    const char *effective_path;
    /**
     * Zero-based top-level occurrence containing this field.
     */
    uintptr_t occurrence;
    /**
     * Inclusive payload byte offset.
     */
    uintptr_t span_start;
    /**
     * Exclusive payload byte offset.
     */
    uintptr_t span_end;
    /**
     * Provenance: 0 schema, 1 unknown, 2 unmatched known, 3 custom decoder.
     */
    uint32_t origin;
    /**
     * Four-byte signature of the containing subrecord.
     */
    uint8_t subrecord_signature[4];
} BethkitFieldMetadata;

/**
 * Returns the major C ABI version implemented by this library.
 */
uint32_t bethkit_abi_version(void);

/**
 * Frees a byte buffer that was returned as an owned allocation by a
 * `bethkit_*` function (e.g. `bethkit_archive_extract`,
 * `bethkit_plugin_writer_write_to_bytes`).
 *
 * Passing a null pointer is a no-op.  The `len` argument must exactly match
 * the `out_len` value written by the producing function.
 *
 * # Safety
 *
 * `ptr` must have been produced by a `bethkit_*` function that transfers
 * ownership to the caller, and `len` must match the corresponding `out_len`.
 * After this call, `ptr` is no longer valid.
 */
void bethkit_bytes_free(uint8_t *ptr, uintptr_t len);

/**
 * Opens a BSA or BA2 archive at `path`.
 *
 * The archive format is detected automatically from the file header.
 * Returns a pointer to the archive handle on success, or null on failure.
 *
 * # Arguments
 *
 * * `path` — NUL-terminated UTF-8 path to the archive file. Borrows.
 *
 * # Errors
 *
 * Returns null and sets the last error when `path` is null or the archive
 * cannot be read or is not a recognized format.
 */
struct BethkitArchive *bethkit_archive_open(const char *path);

/**
 * Frees an archive handle previously returned by [`bethkit_archive_open`].
 *
 * Passing a null pointer is a no-op.  After this call every borrowed handle
 * derived from the archive is invalid.
 */
void bethkit_archive_free(struct BethkitArchive *archive);

/**
 * Returns a pointer to a NUL-terminated string identifying the archive
 * format (e.g. `"BSA"`, `"BA2-GNRL"`).
 *
 * The returned pointer is borrowed from static memory and never needs to be
 * freed.
 *
 * # Errors
 *
 * Returns a pointer to an empty string and sets the last error if `archive`
 * is null.
 */
const char *bethkit_archive_format_name(const struct BethkitArchive *archive);

/**
 * Returns the number of files contained in `archive`.
 *
 * Returns 0 and sets the last error if `archive` is null.
 */
uintptr_t bethkit_archive_file_count(const struct BethkitArchive *archive);

/**
 * Returns a borrowed pointer to the archive entry at `index`, or null if
 * `index` is out of bounds.
 *
 * The returned pointer is borrowed from `archive` and is valid until the
 * archive is freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `archive` is null or `index` is
 * out of bounds.
 */
const BethkitArchiveEntry *bethkit_archive_entry_get(const struct BethkitArchive *archive,
                                                     uintptr_t index);

/**
 * Returns a newly-allocated NUL-terminated copy of the virtual path of
 * `entry` (e.g. `"textures\\actors\\character\\male\\malehead.dds"`).
 *
 * The caller takes ownership of the returned string and must free it with
 * [`bethkit_archive_entry_path_free`].
 *
 * Returns null and sets the last error if `entry` is null or the path
 * contains a NUL byte (which would make it unrepresentable as a C string).
 *
 * # Errors
 *
 * Returns null and sets the last error if `entry` is null or path-to-CString
 * conversion fails.
 */
char *bethkit_archive_entry_path(const BethkitArchiveEntry *entry);

/**
 * Frees a string previously returned by [`bethkit_archive_entry_path`].
 *
 * Passing a null pointer is a no-op.
 */
void bethkit_archive_entry_path_free(char *ptr);

/**
 * Returns the uncompressed file size in bytes for `entry`.
 *
 * Returns 0 and sets the last error if `entry` is null.
 */
uint32_t bethkit_archive_entry_uncompressed_size(const BethkitArchiveEntry *entry);

/**
 * Extracts the file at virtual `path` from `archive` into a heap-allocated
 * buffer.
 *
 * On success, writes the number of bytes into `*out_len` and returns a
 * pointer to the buffer.  The caller takes ownership of this buffer and must
 * free it with [`bethkit_bytes_free`] passing the same `out_len` value.
 *
 * When the virtual path is not found in the archive, returns null and writes
 * `0` into `*out_len` without updating the last error (not-found is not an
 * error; check the return value).
 *
 * # Arguments
 *
 * * `archive`  — Archive to extract from. Borrows.
 * * `path`     — NUL-terminated virtual path of the file to extract. Borrows.
 * * `out_len`  — Written with the byte count on success, or `0` on failure.
 *
 * # Errors
 *
 * Returns null, writes `0` into `*out_len`, and sets the last error if
 * `archive`, `path`, or `out_len` is null, `path` contains invalid UTF-8,
 * or extraction (decompression/I/O) fails.
 */
uint8_t *bethkit_archive_extract(const struct BethkitArchive *archive,
                                 const char *path,
                                 uintptr_t *out_len);

/**
 * Extracts an archive member with an unambiguous status code.
 *
 * Returns 0 and an owned buffer on success (including empty files), 1 for a
 * missing path, or -1 for an error. Release a successful buffer using
 * [`crate::bethkit_bytes_free`] and its exact length. Valid outputs are
 * initialized to null/zero before validation; not-found leaves the last error unchanged.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, invalid UTF-8,
 * extraction errors, or an internal panic.
 *
 * # Safety
 *
 * `archive` must be live, `path` must be NUL-terminated, and outputs must
 * point to separate writable pointer/length slots. The archive is borrowed.
 */
int32_t bethkit_archive_extract_status(const struct BethkitArchive *archive,
                                       const char *path,
                                       uint8_t **out_data,
                                       uintptr_t *out_len);

/**
 * Extracts the file at virtual `path` from `archive` and writes it to
 * `dest` on the file system.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Arguments
 *
 * * `archive` — Archive to extract from. Borrows.
 * * `path`    — NUL-terminated virtual path of the file to extract. Borrows.
 * * `dest`    — NUL-terminated file system destination path. Borrows.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null, the path is
 * not found, extraction fails, or the destination cannot be written.
 */
int32_t bethkit_archive_extract_to_file(const struct BethkitArchive *archive,
                                        const char *path,
                                        const char *dest);

/**
 * Creates a new BSA archive writer for the given `version`.
 *
 * Returns a pointer to the writer handle on success, or null on failure.
 * Must be freed with [`bethkit_bsa_writer_free`] after use (even if
 * [`bethkit_bsa_writer_write_to`] has been called).
 *
 * # Arguments
 *
 * * `version` — The BSA format version to produce.
 */
struct BethkitBsaWriter *bethkit_bsa_writer_new(enum BethkitBsaVersion version);

/**
 * Frees a BSA writer handle.  Passing a null pointer is a no-op.
 */
void bethkit_bsa_writer_free(struct BethkitBsaWriter *w);

/**
 * Enables or disables zlib compression for all files added to `w`.
 *
 * Returns 0 on success or -1 if `w` is null or already consumed.
 */
int32_t bethkit_bsa_writer_set_compress(struct BethkitBsaWriter *w, bool compress);

/**
 * Enables or disables embedding of file names in the BSA data section.
 *
 * Returns 0 on success or -1 if `w` is null or already consumed.
 */
int32_t bethkit_bsa_writer_set_embed_names(struct BethkitBsaWriter *w, bool embed);

/**
 * Adds a file to the BSA writer.
 *
 * `path` is the virtual archive path (e.g. `"textures\\mymod\\foo.dds"`).
 * `data` / `len` are the file contents to pack.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null, or the writer
 * has already been consumed.
 */
int32_t bethkit_bsa_writer_add(struct BethkitBsaWriter *w,
                               const char *path,
                               const uint8_t *data,
                               uintptr_t len);

/**
 * Writes the BSA archive to `dest` on the file system.
 *
 * This call **consumes** the writer; subsequent calls return -1.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Arguments
 *
 * * `w`    — Writer handle. Takes ownership of the inner writer state.
 * * `dest` — NUL-terminated destination path. Borrows.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `w` or `dest` is null, the writer
 * has already been consumed, or writing fails.
 */
int32_t bethkit_bsa_writer_write_to(struct BethkitBsaWriter *w, const char *dest);

/**
 * Creates a new BA2 general-content archive writer for the given `version`.
 *
 * Returns a pointer to the writer handle on success.
 * Must be freed with [`bethkit_ba2_gnrl_writer_free`].
 *
 * # Arguments
 *
 * * `version` — The BA2 format version to produce.
 */
struct BethkitBa2GnrlWriter *bethkit_ba2_gnrl_writer_new(enum BethkitBa2Version version);

/**
 * Frees a BA2 general-content writer handle.  Passing a null pointer is a
 * no-op.
 */
void bethkit_ba2_gnrl_writer_free(struct BethkitBa2GnrlWriter *w);

/**
 * Adds a file to a BA2 general-content writer.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null or the writer
 * has already been consumed.
 */
int32_t bethkit_ba2_gnrl_writer_add(struct BethkitBa2GnrlWriter *w,
                                    const char *path,
                                    const uint8_t *data,
                                    uintptr_t len);

/**
 * Writes the BA2 general-content archive to `dest`.  Consumes the writer.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `w` or `dest` is null, the writer
 * has already been consumed, or writing fails.
 */
int32_t bethkit_ba2_gnrl_writer_write_to(struct BethkitBa2GnrlWriter *w, const char *dest);

/**
 * Creates a new BA2 DX10 (texture) archive writer for the given `version`.
 *
 * Returns a pointer to the writer handle on success.
 * Must be freed with [`bethkit_ba2_dx10_writer_free`].
 *
 * # Arguments
 *
 * * `version` — The BA2 format version to produce.
 */
struct BethkitBa2Dx10Writer *bethkit_ba2_dx10_writer_new(enum BethkitBa2Version version);

/**
 * Frees a BA2 DX10 writer handle.  Passing a null pointer is a no-op.
 */
void bethkit_ba2_dx10_writer_free(struct BethkitBa2Dx10Writer *w);

/**
 * Adds a file to a BA2 DX10 writer.
 *
 * `path` is the virtual archive path (e.g. `"textures\\mymod\\foo.dds"`).
 * `data` / `len` are the raw DDS file bytes to pack.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null, the writer has
 * already been consumed, or `data` does not contain a valid DX10/DDS image.
 */
int32_t bethkit_ba2_dx10_writer_add(struct BethkitBa2Dx10Writer *w,
                                    const char *path,
                                    const uint8_t *data,
                                    uintptr_t len);

/**
 * Writes the BA2 DX10 archive to `dest`.  Consumes the writer.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `w` or `dest` is null, the writer
 * has already been consumed, or writing fails.
 */
int32_t bethkit_ba2_dx10_writer_write_to(struct BethkitBa2Dx10Writer *w, const char *dest);

/**
 * Creates a new, empty plugin cache.
 *
 * Returns a pointer to the handle.  Must be freed with
 * [`bethkit_plugin_cache_free`].
 */
struct BethkitPluginCache *bethkit_plugin_cache_new(void);

/**
 * Frees a plugin cache handle.  Passing a null pointer is a no-op.
 *
 * After this call every record pointer obtained from this cache is invalid.
 */
void bethkit_plugin_cache_free(struct BethkitPluginCache *cache);

/**
 * Adds `plugin` to the cache under `name`.
 *
 * This function **takes ownership** of `plugin`.  The caller must not use
 * or free `plugin` after this call.
 * A valid nonnull plugin is consumed on every return path, including null
 * cache/name, invalid UTF-8, exhausted load-order slots, and internal errors.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `cache`  — Cache to add the plugin to. Borrows.
 * * `name`   — NUL-terminated plugin file name. Borrows.
 * * `plugin` — Plugin handle to add. Ownership transferred.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `cache`, `name`, or `plugin` is
 * null, `name` contains invalid UTF-8, the load order is full, or a panic occurs.
 *
 * # Safety
 *
 * `plugin`, if nonnull, must be an owned live handle that has not been
 * transferred before. `cache` must be exclusively borrowed and `name`
 * must be a readable NUL-terminated string when they are nonnull.
 */
int32_t bethkit_plugin_cache_add(struct BethkitPluginCache *cache,
                                 const char *name,
                                 struct BethkitPlugin *plugin);

/**
 * Returns the number of plugins in the cache.
 *
 * Returns 0 and sets the last error if `cache` is null.
 */
uintptr_t bethkit_plugin_cache_len(const struct BethkitPluginCache *cache);

/**
 * Returns the total number of records across all plugins in the cache.
 *
 * Returns 0 and sets the last error if `cache` is null.
 */
uintptr_t bethkit_plugin_cache_record_count(const struct BethkitPluginCache *cache);

/**
 * Resolves a global FormID (plugin name + object ID) to the winning record.
 *
 * Plugin filenames are matched case-insensitively using the core's canonical form.
 *
 * Returns a borrowed pointer to the record on success, or null if not found.
 * The returned pointer is valid until the cache is freed.
 *
 * # Arguments
 *
 * * `cache`       — Cache to search. Borrows.
 * * `plugin_name` — NUL-terminated plugin file name. Borrows.
 * * `object_id`   — The 24-bit object ID component.
 *
 * # Errors
 *
 * Returns null and sets the last error if `cache` or `plugin_name` is null,
 * or `plugin_name` contains invalid UTF-8.
 */
const BethkitRecord *bethkit_plugin_cache_resolve(const struct BethkitPluginCache *cache,
                                                  const char *plugin_name,
                                                  uint32_t object_id);

/**
 * Searches all plugins in the cache for a record with the given editor ID.
 *
 * On success, writes the global FormID into `*out_gfid` (the `plugin_name`
 * pointer inside is interned into the cache's name arena and valid until the
 * cache is freed) and returns a borrowed pointer to the record.
 *
 * Returns null (without setting the last error) if no matching record is
 * found.  Check the return value to distinguish not-found from an error.
 *
 * # Arguments
 *
 * * `cache`     — Cache to search. Borrows mutably (to intern plugin names).
 * * `edid`      — NUL-terminated editor ID string. Borrows.
 * * `out_gfid`  — Written with the global FormID on success. May be null
 *   (in which case the FormID is not written).
 *
 * # Errors
 *
 * Returns null and sets the last error if `cache` or `edid` is null, or
 * if `edid` is not valid UTF-8.
 */
const BethkitRecord *bethkit_plugin_cache_find_by_editor_id(struct BethkitPluginCache *cache,
                                                            const char *edid,
                                                            struct BethkitGlobalFormId *out_gfid);

/**
 * Returns a pointer to the last error message for the calling thread, or a
 * pointer to an empty string if no error has occurred.
 *
 * # Safety
 *
 * The returned pointer is valid until the next `bethkit_*` FFI call on the
 * same thread. The caller must not free or write through this pointer.
 */
const char *bethkit_last_error(void);

/**
 * Returns the raw integer group type of `group`.
 *
 * The value maps to [`bethkit_core::GroupType`]:
 * 0 = Normal, 1 = WorldChildren, 2 = InteriorCellBlock,
 * 3 = InteriorCellSubBlock, 4 = ExteriorCellBlock,
 * 5 = ExteriorCellSubBlock, 6 = CellChildren, 7 = TopicChildren,
 * 8 = CellPersistentChildren, 9 = CellTemporaryChildren.
 *
 * Returns -1 and sets the last error if `group` is null.
 */
int32_t bethkit_group_type(const BethkitGroup *group);

/**
 * Returns the number of direct children (records or nested groups) in `group`.
 *
 * Returns 0 and sets the last error if `group` is null.
 */
uintptr_t bethkit_group_child_count(const BethkitGroup *group);

/**
 * Returns `true` if the child at `index` is a record, `false` if it is a
 * nested group.
 *
 * Returns `false` and sets the last error if `group` is null or `index` is
 * out of bounds.
 */
bool bethkit_group_child_is_record(const BethkitGroup *group, uintptr_t index);

/**
 * Returns a borrowed pointer to the record at `index`, or null if the child
 * is a nested group or the index is out of bounds.
 *
 * The returned pointer is borrowed from the owning plugin and must not be
 * freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `group` is null, `index` is out
 * of bounds, or the child is not a record.
 */
const BethkitRecord *bethkit_group_child_as_record(const BethkitGroup *group, uintptr_t index);

/**
 * Returns a borrowed pointer to the nested group at `index`, or null if the
 * child is a record or the index is out of bounds.
 *
 * The returned pointer is borrowed from the owning plugin and must not be
 * freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `group` is null, `index` is out
 * of bounds, or the child is not a group.
 */
const BethkitGroup *bethkit_group_child_as_group(const BethkitGroup *group, uintptr_t index);

/**
 * Creates a new, empty load order.
 *
 * Returns a pointer to the handle.  Must be freed with
 * [`bethkit_load_order_free`].
 */
struct BethkitLoadOrder *bethkit_load_order_new(void);

/**
 * Frees a load order handle.  Passing a null pointer is a no-op.
 */
void bethkit_load_order_free(struct BethkitLoadOrder *lo);

/**
 * Appends `name` to the load order with the given plugin `kind`.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `lo` or `name` is null, or `name`
 * contains invalid UTF-8.
 */
int32_t bethkit_load_order_push(struct BethkitLoadOrder *lo,
                                const char *name,
                                enum BethkitPluginKind kind);

/**
 * Returns the number of plugins in the load order.
 *
 * Returns 0 and sets the last error if `lo` is null.
 */
uintptr_t bethkit_load_order_len(const struct BethkitLoadOrder *lo);

/**
 * Resolves `form_id` (as seen in `source_plugin`) to a
 * [`BethkitGlobalFormId`] and writes it into `*out`.
 *
 * This compatibility endpoint assumes no masters. For plugins with masters,
 * use [`bethkit_load_order_resolve_with_plugin`]. Names are returned lowercase.
 *
 * Returns 0 on success, or -1 if the FormID cannot be resolved (e.g.
 * master index out of range).
 *
 * # Arguments
 *
 * * `lo`            — Load order. Borrows.
 * * `form_id`       — The file-local FormID to resolve.
 * * `source_plugin` — NUL-terminated name of the plugin that contains
 *   `form_id`. Borrows.
 * * `out`           — Written with the resolved global FormID on success.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null, `source_plugin`
 * has invalid UTF-8, `source_plugin` is not in the load order, or the master
 * index is out of range.
 */
int32_t bethkit_load_order_resolve(const struct BethkitLoadOrder *lo,
                                   uint32_t form_id,
                                   const char *source_plugin,
                                   struct BethkitGlobalFormId *out);

/**
 * Resolves a file-local FormID using the source plugin's ordered masters.
 *
 * Borrows `lo` and `plugin`; `source_plugin` is the source filename. Writes
 * `out` and returns 0 on success. Its name is borrowed until `lo` is freed.
 *
 * # Errors
 *
 * Returns -1 for null pointers, invalid UTF-8, unregistered source or owner,
 * invalid master indexes, or an internal panic. The output remains unchanged.
 *
 * # Safety
 *
 * Handles must be live, `source_plugin` must be a readable NUL-terminated
 * string, and `out` must point to writable storage for one global ID.
 */
int32_t bethkit_load_order_resolve_with_plugin(const struct BethkitLoadOrder *lo,
                                               uint32_t form_id,
                                               const char *source_plugin,
                                               const struct BethkitPlugin *plugin,
                                               struct BethkitGlobalFormId *out);

/**
 * Copies a plugin into an independently owned patch session.
 *
 * Borrows `plugin` only during this call. Returns an owned handle to free with
 * [`bethkit_plugin_patcher_free`], or null on failure.
 *
 * # Errors
 *
 * Returns null and sets the last error for a null plugin, parse errors, or panics.
 *
 * # Safety
 *
 * `plugin` must be a live borrowed plugin handle.
 */
struct BethkitPluginPatcher *bethkit_plugin_patcher_new(const struct BethkitPlugin *plugin);

/**
 * Frees a patch session. A null pointer is a no-op.
 *
 * # Safety
 *
 * A nonnull `patcher` must be an owned handle from
 * [`bethkit_plugin_patcher_new`] that has not already been freed.
 */
void bethkit_plugin_patcher_free(struct BethkitPluginPatcher *patcher);

/**
 * Copies a writable record as the replacement for an existing `form_id`.
 *
 * Returns 0 on success. Borrows both handles without consuming them. The
 * replacement must retain the original FormID and record signature. Repeated
 * calls for the same ID replace the previous edit. Compressed input flags are
 * cleared because writable payloads are serialized uncompressed.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null handles, a missing source record,
 * mismatching identity/signature, unsupported source games, or panics.
 *
 * # Safety
 *
 * `patcher` must be live and exclusively borrowed. `record` must be a live
 * writable record and must not alias `patcher`.
 */
int32_t bethkit_plugin_patcher_replace_record(struct BethkitPluginPatcher *patcher,
                                              uint32_t form_id,
                                              const struct BethkitWritableRecord *record);

/**
 * Serializes a patch session into an owned byte buffer without consuming it.
 *
 * Returns 0 on success or -1 on failure. Free the successful buffer using
 * [`crate::bethkit_bytes_free`] with the exact returned length. Valid outputs
 * are initialized to null/zero before validation.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, encoding errors, or panics.
 *
 * # Safety
 *
 * `patcher` must be a live borrowed handle. Outputs must point to distinct
 * writable pointer and length slots without aliasing the handle.
 */
int32_t bethkit_plugin_patcher_write_to_bytes(const struct BethkitPluginPatcher *patcher,
                                              uint8_t **out_data,
                                              uintptr_t *out_len);

/**
 * Serializes a patch session to a destination file without consuming it.
 *
 * Returns 0 on success. The session owns its input bytes, so overwriting the
 * original path cannot invalidate it. The destination is replaced, not appended.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null arguments, invalid UTF-8,
 * serialization or file I/O errors, or panics.
 *
 * # Safety
 *
 * `patcher` must be a live borrowed handle. `path` must be NUL-terminated UTF-8.
 */
int32_t bethkit_plugin_patcher_write_to_file(const struct BethkitPluginPatcher *patcher,
                                             const char *path);

/**
 * Opens a plugin file from `path` for the specified `game`.
 *
 * Returns a pointer to the plugin handle on success, or null on failure
 * (call [`bethkit_last_error`] for details).  The caller owns the returned
 * handle and must free it with [`bethkit_plugin_free`].
 *
 * # Arguments
 *
 * * `path`  — NUL-terminated UTF-8 path to the plugin file. Borrows.
 * * `game`  — The game the plugin was created for.
 *
 * # Errors
 *
 * Returns null and sets the last error when `path` is null, the path is not
 * valid UTF-8, or the plugin file cannot be parsed.
 */
struct BethkitPlugin *bethkit_plugin_open(const char *path, enum BethkitGame game);

/**
 * Opens a plugin from a byte slice already loaded in memory.
 *
 * Returns a pointer to the plugin handle on success, or null on failure.
 * The caller owns the returned handle and must free it with
 * [`bethkit_plugin_free`].
 *
 * # Arguments
 *
 * * `data` — Pointer to the first byte of the plugin data. Borrows.
 * * `len`  — Number of bytes in `data`.
 * * `game` — The game the plugin was created for.
 *
 * # Errors
 *
 * Returns null and sets the last error when `data` is null or the bytes
 * cannot be parsed as a valid plugin.
 */
struct BethkitPlugin *bethkit_plugin_open_from_bytes(const uint8_t *data,
                                                     uintptr_t len,
                                                     enum BethkitGame game);

/**
 * Frees a plugin handle previously returned by [`bethkit_plugin_open`] or
 * [`bethkit_plugin_open_from_bytes`].
 *
 * Passing a null pointer is a no-op.  After this call every borrowed handle
 * derived from `plugin` (records, groups, subrecords) is invalid.
 */
void bethkit_plugin_free(struct BethkitPlugin *plugin);

/**
 * Returns the [`BethkitPluginKind`] (Full, Light, or Overlay) of `plugin`.
 *
 * # Errors
 *
 * Returns [`BethkitPluginKind::Full`] as a sentinel and sets the last error
 * if `plugin` is null.
 */
enum BethkitPluginKind bethkit_plugin_kind(const struct BethkitPlugin *plugin);

/**
 * Returns `true` if the plugin has the LOCALIZED flag set, `false` otherwise.
 *
 * # Errors
 *
 * Returns `false` and sets the last error if `plugin` is null.
 */
bool bethkit_plugin_is_localized(const struct BethkitPlugin *plugin);

/**
 * Returns the number of master files listed in the plugin header.
 *
 * # Errors
 *
 * Returns 0 and sets the last error if `plugin` is null.
 */
uintptr_t bethkit_plugin_master_count(const struct BethkitPlugin *plugin);

/**
 * Returns a pointer to the NUL-terminated master file name at `index`, or
 * null if `index` is out of bounds.
 *
 * The returned pointer is borrowed from `plugin` and is valid until
 * [`bethkit_plugin_free`] is called.
 *
 * # Errors
 *
 * Returns null and sets the last error if `plugin` is null or `index` is
 * out of bounds.
 */
const char *bethkit_plugin_master_get(const struct BethkitPlugin *plugin, uintptr_t index);

/**
 * Returns a pointer to the NUL-terminated plugin description, or null if the
 * plugin has no description.
 *
 * The returned pointer is borrowed from `plugin` and is valid until
 * [`bethkit_plugin_free`] is called.
 *
 * # Errors
 *
 * Returns null and sets the last error if `plugin` is null.
 */
const char *bethkit_plugin_description(const struct BethkitPlugin *plugin);

/**
 * Returns the number of top-level record groups in `plugin`.
 *
 * # Errors
 *
 * Returns 0 and sets the last error if `plugin` is null.
 */
uintptr_t bethkit_plugin_group_count(const struct BethkitPlugin *plugin);

/**
 * Returns a borrowed pointer to the group at `index`, or null if `index` is
 * out of bounds.
 *
 * The returned pointer is borrowed from `plugin` and must not be freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `plugin` is null or `index` is
 * out of bounds.
 */
const BethkitGroup *bethkit_plugin_group_get(const struct BethkitPlugin *plugin, uintptr_t index);

/**
 * Searches for a record with the given `form_id` inside `plugin`.
 *
 * Returns a borrowed pointer to the first matching record, or null if not
 * found.  The returned pointer is borrowed from `plugin` and must not be
 * freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `plugin` is null.
 */
const BethkitRecord *bethkit_plugin_find_record(const struct BethkitPlugin *plugin,
                                                uint32_t form_id);

/**
 * Writes the 4-byte record signature into `out`.
 *
 * `out` must point to at least 4 writable bytes.
 *
 * Returns 0 on success or -1 if `record` or `out` is null.
 */
int32_t bethkit_record_signature(const BethkitRecord *record, uint8_t *out);

/**
 * Returns the raw FormID of `record`.
 *
 * Returns 0 and sets the last error if `record` is null.
 */
uint32_t bethkit_record_form_id(const BethkitRecord *record);

/**
 * Returns the raw record flags of `record`.
 *
 * Returns 0 and sets the last error if `record` is null.
 */
uint32_t bethkit_record_flags(const BethkitRecord *record);

/**
 * Returns the form version stored in the record header.
 *
 * Returns 0 and sets the last error if `record` is null.
 */
uint16_t bethkit_record_form_version(const BethkitRecord *record);

/**
 * Returns a pointer to the NUL-terminated editor ID (EDID subrecord) of
 * `record`, or null if the record has no EDID.
 *
 * The returned string is independently owned and must be freed with
 * [`bethkit_record_editor_id_free`], even after its plugin is freed.
 *
 * Returns null on error (null record, I/O error, or encoding error).
 *
 * # Errors
 *
 * Returns null and sets the last error if `record` is null or the EDID
 * subrecord cannot be decoded.
 */
const char *bethkit_record_editor_id(const BethkitRecord *record);

/**
 * Reads an editor ID, distinguishing a missing EDID from a decoding error.
 *
 * Returns 0 and an owned string, 1 if absent, or -1 on error. Release the
 * result using [`bethkit_record_editor_id_free`]. A valid `out` is initialized
 * to null before validation. Not-found does not change the last error.
 *
 * # Errors
 *
 * Returns -1 for null arguments, decoding errors, interior NULs, or panics.
 *
 * # Safety
 *
 * `record` must be a live borrowed record. `out` must point to writable
 * pointer storage that does not alias the record.
 */
int32_t bethkit_record_editor_id_status(const BethkitRecord *record, char **out);

/**
 * Frees an editor ID string previously returned by [`bethkit_record_editor_id`].
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `ptr` must have been returned by [`bethkit_record_editor_id`] or
 * [`bethkit_record_editor_id_status`] and not yet freed.
 */
void bethkit_record_editor_id_free(char *ptr);

/**
 * Returns the number of subrecords in `record`, or -1 on error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `record` is null or the subrecords
 * cannot be decoded.
 */
int64_t bethkit_record_subrecord_count(const BethkitRecord *record);

/**
 * Returns a borrowed pointer to the subrecord at `index`, or null if
 * `index` is out of bounds or on error.
 *
 * The returned pointer is borrowed from the record's owning plugin and must
 * not be freed.
 *
 * # Errors
 *
 * Returns null and sets the last error if `record` is null, subrecords
 * cannot be decoded, or `index` is out of bounds.
 */
const BethkitSubRecord *bethkit_record_subrecord_get(const BethkitRecord *record, uintptr_t index);

/**
 * Returns a borrowed pointer to the first subrecord whose signature matches
 * the 4-byte `sig`, or null if not found.
 *
 * `sig` must point to exactly 4 readable bytes.
 *
 * # Errors
 *
 * Returns null and sets the last error if `record` or `sig` is null, or
 * subrecords cannot be decoded.
 */
const BethkitSubRecord *bethkit_record_subrecord_find(const BethkitRecord *record,
                                                      const uint8_t *sig);

/**
 * Writes the 4-byte subrecord signature into `out`.
 *
 * `out` must point to at least 4 writable bytes.
 *
 * Returns 0 on success or -1 if `sr` or `out` is null.
 */
int32_t bethkit_subrecord_signature(const BethkitSubRecord *sr, uint8_t *out);

/**
 * Returns a [`BethkitSlice`] pointing to the raw bytes of `sr`.
 *
 * The slice is borrowed from the owning plugin and is valid until the plugin
 * is freed.  Returns a zero-length null slice on error.
 *
 * # Errors
 *
 * Returns a `{ ptr: null, len: 0 }` slice and sets the last error if `sr`
 * is null.
 */
struct BethkitSlice bethkit_subrecord_bytes(const BethkitSubRecord *sr);

/**
 * Reads the subrecord payload as a single `u8`.
 *
 * Writes the decoded value into `*out` and returns 0 on success, or -1 on
 * error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `sr` or `out` is null, or the
 * payload length does not match.
 */
int32_t bethkit_subrecord_as_u8(const BethkitSubRecord *sr, uint8_t *out);

/**
 * Reads the subrecord payload as a little-endian `u16`.
 *
 * Writes the decoded value into `*out` and returns 0 on success, or -1 on
 * error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `sr` or `out` is null, or the
 * payload length does not match.
 */
int32_t bethkit_subrecord_as_u16(const BethkitSubRecord *sr, uint16_t *out);

/**
 * Reads the subrecord payload as a little-endian `u32`.
 *
 * Writes the decoded value into `*out` and returns 0 on success, or -1 on
 * error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `sr` or `out` is null, or the
 * payload length does not match.
 */
int32_t bethkit_subrecord_as_u32(const BethkitSubRecord *sr, uint32_t *out);

/**
 * Reads the subrecord payload as a little-endian `f32`.
 *
 * Writes the decoded value into `*out` and returns 0 on success, or -1 on
 * error.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `sr` or `out` is null, or the
 * payload length does not match.
 */
int32_t bethkit_subrecord_as_f32(const BethkitSubRecord *sr, float *out);

/**
 * Returns a pointer to the NUL-terminated string content of `sr`.
 *
 * The returned pointer is heap-allocated for this call. Use
 * [`bethkit_record_editor_id_free`] (which accepts any CString produced this
 * way) — or more precisely, call [`bethkit_zstring_free`] — to release it.
 *
 * Returns null on error.
 *
 * # Errors
 *
 * Returns null and sets the last error if `sr` is null or the payload is not
 * valid UTF-8.
 */
char *bethkit_subrecord_as_zstring(const BethkitSubRecord *sr);

/**
 * Frees a NUL-terminated string produced by [`bethkit_subrecord_as_zstring`]
 * or [`bethkit_record_editor_id`].
 *
 * Passing a null pointer is a no-op.
 *
 * # Safety
 *
 * `ptr` must have been produced by one of the above functions and not yet
 * freed.
 */
void bethkit_zstring_free(char *ptr);

/**
 * Loads the release-time embedded schema catalog.
 *
 * Returns null and sets the last error when this library was built without
 * an embedded schema source or the embedded data is invalid.
 */
struct BethkitSchemaCatalog *bethkit_schema_catalog_embedded(void);

/**
 * Loads a schema catalog bundle from `path`.
 *
 * Returns null and sets the last error when the path or bundle is invalid.
 */
struct BethkitSchemaCatalog *bethkit_schema_catalog_open(const char *path);

/**
 * Frees an owned schema catalog. Passing null is a no-op.
 */
void bethkit_schema_catalog_free(struct BethkitSchemaCatalog *catalog);

/**
 * Returns an owned package handle for `game`.
 *
 * Returns null and sets the last error when the catalog does not contain the
 * requested game.
 */
struct BethkitSchemaPackage *bethkit_schema_catalog_package(const struct BethkitSchemaCatalog *catalog,
                                                            enum BethkitGame game);

/**
 * Opens one `.bkschema` package from `path`.
 */
struct BethkitSchemaPackage *bethkit_schema_package_open(const char *path);

/**
 * Frees an owned schema-package handle. Passing null is a no-op.
 */
void bethkit_schema_package_free(struct BethkitSchemaPackage *package);

/**
 * Returns an owned UTF-8 JSON representation of the package manifest.
 *
 * `package` is borrowed for this call. Free the result with [`bethkit_string_free`].
 * Field names and enum values match the serialized schema manifest.
 *
 * # Errors
 *
 * Returns null and sets the last error for a null package or serialization failure.
 *
 * # Safety
 *
 * A non-null `package` must point to a live package handle.
 */
char *bethkit_schema_package_manifest_json(const struct BethkitSchemaPackage *package);

/**
 * Returns an owned JSON document containing the complete serializable schema graph.
 *
 * The document contains `format_version` (1), `manifest`, `records`,
 * `callback_bindings`, `condition_function_table`, and `payload_sha256`.
 * Schema signatures retain their four-byte JSON array representation. Node order
 * matches the package and serialization is deterministic for the same package.
 * Free the returned string with [`bethkit_string_free`].
 *
 * # Errors
 *
 * Returns null and sets the last error for a null package or serialization failure.
 *
 * # Safety
 *
 * A non-null `package` must point to a live package handle.
 */
char *bethkit_schema_package_graph_json(const struct BethkitSchemaPackage *package);

/**
 * Frees an owned string returned by a function that names this release function.
 *
 * Passing null is a no-op. The pointer becomes invalid after this call.
 *
 * # Safety
 *
 * `ptr` must be null or an allocation returned by a compatible Bethkit function
 * that has not already been freed. Borrowed strings must never be passed here.
 */
void bethkit_string_free(char *ptr);

/**
 * Returns structured validation diagnostics as an owned UTF-8 JSON document.
 *
 * `context` and `record` are borrowed for this call. Set `localized` from the
 * containing plugin. `mode` is 0 for strict validation or 1 for xEdit-compatible
 * missing-required-field warnings. Free the result with [`bethkit_string_free`].
 * The document contains `format_version` (1), `has_errors`, and `diagnostics`.
 * Each diagnostic includes severity, code, message, record_signature, form_id,
 * and nullable node_id, path, and span. Severity and code use snake_case strings.
 *
 * # Errors
 *
 * Returns null and sets the last error for null handles, an unsupported mode,
 * a missing record schema, or serialization failure. Record validation errors
 * are reported in the JSON document, not as an API failure.
 *
 * # Safety
 *
 * Both non-null handles must remain valid for this call.
 */
char *bethkit_semantic_validate_json(const struct BethkitSemanticContext *context,
                                     const BethkitRecord *record,
                                     bool localized,
                                     uint32_t mode);

/**
 * Creates a semantic context for `package` and the built-in decoders.
 */
struct BethkitSemanticContext *bethkit_semantic_context_new(const struct BethkitSchemaPackage *package);

/**
 * Frees an owned semantic context. Passing null is a no-op.
 */
void bethkit_semantic_context_free(struct BethkitSemanticContext *context);

/**
 * Creates a lossless semantic editor for `record`.
 */
struct BethkitRecordEditor *bethkit_record_editor_new(const struct BethkitSemanticContext *context,
                                                      const BethkitRecord *record,
                                                      bool localized);

/**
 * Frees an owned record editor. Passing null is a no-op.
 */
void bethkit_record_editor_free(struct BethkitRecordEditor *editor);

/**
 * Sets one signed integer field occurrence.
 */
int32_t bethkit_record_editor_set_i64(struct BethkitRecordEditor *editor,
                                      const char *path,
                                      uintptr_t occurrence,
                                      int64_t value);

/**
 * Sets one unsigned integer field occurrence.
 */
int32_t bethkit_record_editor_set_u64(struct BethkitRecordEditor *editor,
                                      const char *path,
                                      uintptr_t occurrence,
                                      uint64_t value);

/**
 * Sets one floating-point field occurrence.
 */
int32_t bethkit_record_editor_set_f64(struct BethkitRecordEditor *editor,
                                      const char *path,
                                      uintptr_t occurrence,
                                      double value);

/**
 * Sets one FormID field occurrence.
 */
int32_t bethkit_record_editor_set_form_id(struct BethkitRecordEditor *editor,
                                          const char *path,
                                          uintptr_t occurrence,
                                          uint32_t value);

/**
 * Sets one UTF-8 string field occurrence.
 */
int32_t bethkit_record_editor_set_string(struct BethkitRecordEditor *editor,
                                         const char *path,
                                         uintptr_t occurrence,
                                         const char *value);

/**
 * Sets one raw-byte field occurrence.
 *
 * `value` must point to `length` readable bytes.
 */
int32_t bethkit_record_editor_set_bytes(struct BethkitRecordEditor *editor,
                                        const char *path,
                                        uintptr_t occurrence,
                                        const uint8_t *value,
                                        uintptr_t length);

/**
 * Removes one top-level field occurrence.
 */
int32_t bethkit_record_editor_remove(struct BethkitRecordEditor *editor,
                                     const char *path,
                                     uintptr_t occurrence);

/**
 * Consumes an editor's contents and returns an owned writable record.
 *
 * The returned record must be freed with `bethkit_writable_record_free` or
 * transferred to a writable group. The editor handle itself remains allocated
 * and must still be freed with [`bethkit_record_editor_free`]. Further editing
 * or finishing calls fail because its contents have already been consumed.
 */
struct BethkitWritableRecord *bethkit_record_editor_finish(struct BethkitRecordEditor *editor);

/**
 * Creates a schema-guided snapshot of all decoded fields in `record`.
 *
 * Uses the schema package owned by `context`. Unknown subrecords remain
 * visible as raw bytes.
 *
 * `localized` should be `true` when the plugin that contains `record` has
 * its LOCALIZED flag set; see [`bethkit_plugin_is_localized`].
 *
 * Returns a pointer to the view on success, or null on error.  Must be
 * freed with [`bethkit_record_view_free`].
 *
 * # Arguments
 *
 * * `context` - Semantic context used to decode the record. Borrows.
 * * `record` - Record to inspect. Borrows.
 * * `localized` - Whether the parent plugin is localized.
 *
 * # Errors
 *
 * Returns null and sets the last error if a handle is null or decoding fails.
 *
 * # Safety
 *
 * Both handles must remain valid for this call. The returned snapshot owns all
 * decoded data and does not retain either handle.
 */
struct BethkitRecordView *bethkit_record_view_new(const struct BethkitSemanticContext *context,
                                                  const BethkitRecord *record,
                                                  bool localized);

/**
 * Frees a record view and recursively all owned sub-objects — nested
 * [`BethkitFieldEntries`] (struct fields), [`BethkitFieldValues`] (array
 * fields), and flags-name arrays.  All `name` and `str_val` pointers
 * borrowed from the view become invalid after this call.
 *
 * Passing a null pointer is a no-op.
 */
void bethkit_record_view_free(struct BethkitRecordView *view);

/**
 * Returns the number of fields in the view.
 *
 * Returns 0 and sets the last error if `view` is null.
 */
uintptr_t bethkit_record_view_field_count(const struct BethkitRecordView *view);

/**
 * Returns a borrowed pointer to the field at `index`, or null if out of
 * bounds.
 *
 * The returned pointer is borrowed from `view` and is valid until
 * [`bethkit_record_view_free`] is called.
 *
 * # Errors
 *
 * Returns null and sets the last error if `view` is null or `index` is out
 * of bounds.
 */
const struct BethkitNamedField *bethkit_record_view_field_get(const struct BethkitRecordView *view,
                                                              uintptr_t index);

/**
 * Copies the metadata for top-level field `index` into caller-owned `out`.
 *
 * Returns 0 on success. Strings in `out` are borrowed from `view` and remain
 * valid until the view is freed. The output remains unchanged on failure.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for a null pointer or an invalid index.
 *
 * # Safety
 *
 * `view` must be a live view and `out` must point to writable, aligned storage
 * for one [`BethkitFieldMetadata`].
 */
int32_t bethkit_record_view_field_metadata(const struct BethkitRecordView *view,
                                           uintptr_t index,
                                           struct BethkitFieldMetadata *out);

/**
 * Copies metadata for nested field `index` into caller-owned `out`.
 *
 * Returns 0 on success. Paths retain their schema identity and union selection;
 * occurrence, provenance, and subrecord signature identify the containing
 * top-level field. Array positions are represented by traversal of the value
 * tree. Strings belong to the owning view. Output remains unchanged on failure.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for a null pointer or an invalid index.
 *
 * # Safety
 *
 * `entries` and its owning view must remain alive. `out` must point to writable,
 * aligned storage for one [`BethkitFieldMetadata`].
 */
int32_t bethkit_field_entries_metadata(const struct BethkitFieldEntries *entries,
                                       uintptr_t index,
                                       struct BethkitFieldMetadata *out);

/**
 * Returns the number of entries in a struct field list.
 *
 * Returns 0 and sets the last error if `entries` is null.
 */
uintptr_t bethkit_field_entries_len(const struct BethkitFieldEntries *entries);

/**
 * Returns a borrowed pointer to the named field at `index` in `entries`, or
 * null if `index` is out of bounds.
 *
 * # Errors
 *
 * Returns null and sets the last error if `entries` is null or `index` is
 * out of bounds.
 */
const struct BethkitNamedField *bethkit_field_entries_get(const struct BethkitFieldEntries *entries,
                                                          uintptr_t index);

/**
 * Frees a **detached** field entries list — one explicitly owned by the
 * caller and not embedded in a [`BethkitRecordView`].
 *
 * **Do not call this on values obtained from a [`BethkitRecordView`].**
 * [`bethkit_record_view_free`] handles recursive cleanup automatically;
 * calling this on view-owned entries causes a double-free.
 *
 * Passing a null pointer is a no-op.
 */
void bethkit_field_entries_free(struct BethkitFieldEntries *entries);

/**
 * Returns the number of values in an array field list.
 *
 * Returns 0 and sets the last error if `values` is null.
 */
uintptr_t bethkit_field_values_len(const struct BethkitFieldValues *values);

/**
 * Returns a borrowed pointer to the value at `index` in `values`, or null
 * if `index` is out of bounds.
 *
 * # Errors
 *
 * Returns null and sets the last error if `values` is null or `index` is
 * out of bounds.
 */
const struct BethkitFieldValue *bethkit_field_values_get(const struct BethkitFieldValues *values,
                                                         uintptr_t index);

/**
 * Frees a **detached** field values list — one explicitly owned by the
 * caller and not embedded in a [`BethkitRecordView`].
 *
 * **Do not call this on values obtained from a [`BethkitRecordView`].**
 * [`bethkit_record_view_free`] handles recursive cleanup automatically;
 * calling this on view-owned values causes a double-free.
 *
 * Passing a null pointer is a no-op.
 */
void bethkit_field_values_free(struct BethkitFieldValues *values);

/**
 * Returns an owned, structurally addressed snapshot as a UTF-8 JSON document.
 *
 * Borrow `context` and `record` for this call and set `localized` from the plugin.
 * Free the result with `bethkit_string_free`. The document contains version 1,
 * schema and structure hashes, record identity, and ordered fields. Every value,
 * including array items, carries its exact native address.
 *
 * # Errors
 *
 * Returns null and sets the last error for null handles, decoding failure, or
 * serialization failure.
 *
 * # Safety
 *
 * Non-null handles must remain valid for this call.
 */
char *bethkit_semantic_snapshot_json(const struct BethkitSemanticContext *context,
                                     const BethkitRecord *record,
                                     bool localized);

/**
 * Returns an owned JSON snapshot of an editor's current normalized record state.
 *
 * Free the result with `bethkit_string_free`. Obtain fresh addresses after a
 * structural edit; addresses from before after-load normalization may be stale.
 *
 * # Errors
 *
 * Returns null and sets the last error for null or consumed editors, decoding
 * failure, or serialization failure.
 *
 * # Safety
 *
 * A non-null editor must remain valid for this call.
 */
char *bethkit_record_editor_snapshot_json(const struct BethkitRecordEditor *editor);

/**
 * Replaces the exact value selected by a native snapshot address.
 *
 * Both JSON strings are borrowed NUL-terminated UTF-8. `value_json` uses the
 * snapshot's tagged value representation; extra snapshot metadata is accepted.
 * Returns 0 on success; the editor retains ownership of all copied values.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for invalid JSON, a null or consumed editor,
 * a stale address, or a schema-invalid edit. Failed edits leave the editor unchanged.
 *
 * # Safety
 *
 * The editor must be live and both strings must be valid for this call.
 */
int32_t bethkit_record_editor_set_at_json(struct BethkitRecordEditor *editor,
                                          const char *address_json,
                                          const char *value_json);

/**
 * Inserts a value before an array item or appends to an addressed array.
 *
 * A whole non-array subrecord address inserts a same-path occurrence before it
 * when grammar permits. Both JSON strings are borrowed. Returns 0 on success.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for malformed JSON, null or consumed handles,
 * stale addresses, or invalid insertion. The editor remains unchanged on failure.
 *
 * # Safety
 *
 * The editor and NUL-terminated UTF-8 strings must remain valid for this call.
 */
int32_t bethkit_record_editor_insert_at_json(struct BethkitRecordEditor *editor,
                                             const char *address_json,
                                             const char *value_json);

/**
 * Removes an addressed subrecord, array item, or optional packed member.
 *
 * `address_json` is borrowed NUL-terminated UTF-8. Returns 0 on success.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for invalid JSON, stale addresses, a null or
 * consumed editor, or schema-invalid removal. Failure leaves the editor unchanged.
 *
 * # Safety
 *
 * The editor and address string must remain valid for this call.
 */
int32_t bethkit_record_editor_remove_at_json(struct BethkitRecordEditor *editor,
                                             const char *address_json);

/**
 * Creates a new, empty string table for the given `kind`.
 *
 * Returns a pointer to the handle.  Must be freed with
 * [`bethkit_string_table_free`].
 *
 * # Arguments
 *
 * * `kind` — The string file type to create.
 */
struct BethkitStringTable *bethkit_string_table_new(enum BethkitStringFileKind kind);

/**
 * Opens and parses a string table from a file at `path`.
 *
 * The file format (null-terminated vs. length-prefixed) is inferred from
 * the file extension.
 *
 * Returns a pointer to the handle on success, or null on failure.  Must be
 * freed with [`bethkit_string_table_free`].
 *
 * # Arguments
 *
 * * `path` — NUL-terminated UTF-8 path to the string table file. Borrows.
 *
 * # Errors
 *
 * Returns null and sets the last error if `path` is null, the file cannot
 * be read, or the data is malformed.
 */
struct BethkitStringTable *bethkit_string_table_open(const char *path);

/**
 * Frees a string table handle.  Passing a null pointer is a no-op.
 */
void bethkit_string_table_free(struct BethkitStringTable *st);

/**
 * Returns the [`BethkitStringFileKind`] of `st`.
 *
 * Returns [`BethkitStringFileKind::Strings`] as a sentinel and sets the last
 * error if `st` is null.
 */
enum BethkitStringFileKind bethkit_string_table_kind(const struct BethkitStringTable *st);

/**
 * Returns the number of entries in `st`.
 *
 * Returns 0 and sets the last error if `st` is null.
 */
uintptr_t bethkit_string_table_len(const struct BethkitStringTable *st);

/**
 * Looks up the string with `id` in `st`.
 *
 * On success, writes the byte count into `*out_len` and returns a pointer
 * to the raw string bytes.  The bytes are **borrowed** from the table and
 * are valid until the table is mutated or freed.
 *
 * When `id` is not present in the table, returns null and writes `0` into
 * `*out_len` without setting the last error.
 *
 * # Arguments
 *
 * * `st`      — String table. Borrows.
 * * `id`      — String table entry ID.
 * * `out_len` — Written with the byte count on success, or `0` if not found.
 *
 * # Errors
 *
 * Returns null, writes `0` into `*out_len`, and sets the last error if
 * `st` or `out_len` is null.
 */
const uint8_t *bethkit_string_table_get(const struct BethkitStringTable *st,
                                        uint32_t id,
                                        uintptr_t *out_len);

/**
 * Inserts or replaces the entry with `id` in `st`.
 *
 * Returns 0 on success or -1 if `st` or `data` is null.
 *
 * # Arguments
 *
 * * `st`   — String table. Borrows.
 * * `id`   — Entry ID to insert.
 * * `data` — Pointer to the byte payload. Borrows.
 * * `len`  — Number of bytes in `data`.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `st` or `data` is null.
 */
int32_t bethkit_string_table_insert(struct BethkitStringTable *st,
                                    uint32_t id,
                                    const uint8_t *data,
                                    uintptr_t len);

/**
 * Inserts a new entry with an auto-assigned ID and writes that ID into
 * `*out_id`.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `st`     — String table. Borrows.
 * * `data`   — Pointer to the byte payload. Borrows.
 * * `len`    — Number of bytes in `data`.
 * * `out_id` — Written with the assigned ID on success.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `st`, `data`, or `out_id` is null.
 */
int32_t bethkit_string_table_insert_new(struct BethkitStringTable *st,
                                        const uint8_t *data,
                                        uintptr_t len,
                                        uint32_t *out_id);

/**
 * Removes the entry with `id` from `st`.
 *
 * Returns `true` if the entry was present, `false` if it was absent.
 *
 * # Errors
 *
 * Returns `false` and sets the last error if `st` is null.
 */
bool bethkit_string_table_remove(struct BethkitStringTable *st, uint32_t id);

/**
 * Serializes `st` to a file at `path`.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Arguments
 *
 * * `st`   — String table. Borrows.
 * * `path` — NUL-terminated UTF-8 destination path. Borrows.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `st` or `path` is null, or writing
 * fails.
 */
int32_t bethkit_string_table_write_to_file(const struct BethkitStringTable *st, const char *path);

/**
 * Creates a new, empty localization set.
 *
 * Returns a pointer to the handle.  Must be freed with
 * [`bethkit_localization_set_free`].
 */
struct BethkitLocalizationSet *bethkit_localization_set_new(void);

/**
 * Copies all string payloads into an independent, owned localization set.
 *
 * Borrows `ls` during the call. The returned handle must be freed with
 * [`bethkit_localization_set_free`]. Later mutations affect only the copy.
 *
 * # Errors
 *
 * Returns null and sets the last error for a null handle or an internal panic.
 *
 * # Safety
 *
 * `ls` must be a live borrowed localization-set handle.
 */
struct BethkitLocalizationSet *bethkit_localization_set_clone(const struct BethkitLocalizationSet *ls);

/**
 * Inserts a payload under a fresh nonzero ID in the selected table.
 *
 * Returns 0 and writes the assigned ID to `out_id`, or -1 without modifying
 * the table or output on failure. Existing IDs are never overwritten, including
 * when the table already contains `UINT32_MAX`. Borrows all pointers.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, exhausted IDs, or panics.
 *
 * # Safety
 *
 * `ls` must be a live exclusively borrowed set. `data` must point to `len`
 * readable bytes. `out_id` must be writable and must not alias the set or data.
 */
int32_t bethkit_localization_set_insert_new(struct BethkitLocalizationSet *ls,
                                            enum BethkitStringFileKind kind,
                                            const uint8_t *data,
                                            uintptr_t len,
                                            uint32_t *out_id);

/**
 * Removes an entry from a borrowed localization set.
 *
 * Returns 0 if removed, 1 if absent, or -1 on error. Does not remove references
 * from plugins; callers must ensure no live field still uses the entry.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for a null handle or an internal panic.
 *
 * # Safety
 *
 * `ls` must be a live exclusively borrowed localization set.
 */
int32_t bethkit_localization_set_remove(struct BethkitLocalizationSet *ls,
                                        enum BethkitStringFileKind kind,
                                        uint32_t id);

/**
 * Serializes one selected table into an independently owned byte buffer.
 *
 * Returns 0 on success or -1 on failure. Release the result with
 * [`crate::bethkit_bytes_free`] and the exact returned length. Outputs are
 * initialized to null/zero before handle validation; the set is not consumed.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, encoding errors, or panics.
 *
 * # Safety
 *
 * `ls` must be a live borrowed set. Outputs must be distinct writable slots
 * that do not alias the set.
 */
int32_t bethkit_localization_set_table_to_bytes(const struct BethkitLocalizationSet *ls,
                                                enum BethkitStringFileKind kind,
                                                uint8_t **out_data,
                                                uintptr_t *out_len);

/**
 * Opens and parses the three sibling string tables for `plugin_path` and
 * `language`.
 *
 * The three files are expected to follow the Skyrim naming convention:
 * `<stem>_<language>.strings`, `…dlstrings`, and `…ilstrings`.
 *
 * Returns a pointer to the handle on success, or null on failure.  Must be
 * freed with [`bethkit_localization_set_free`].
 *
 * # Arguments
 *
 * * `plugin_path` — NUL-terminated path to the `.esp`/`.esm` file. Borrows.
 * * `language`    — NUL-terminated language code (e.g. `"english"`). Borrows.
 *
 * # Errors
 *
 * Returns null and sets the last error if any pointer is null, the paths
 * contain invalid UTF-8, or any string table file cannot be read.
 */
struct BethkitLocalizationSet *bethkit_localization_set_open(const char *plugin_path,
                                                             const char *language);

/**
 * Frees a localization set handle.  Passing a null pointer is a no-op.
 */
void bethkit_localization_set_free(struct BethkitLocalizationSet *ls);

/**
 * Looks up string `id` of type `kind` in `ls`.
 *
 * On success, writes the byte count into `*out_len` and returns a pointer
 * to the raw bytes.  The bytes are borrowed from the set and are valid until
 * the set is mutated or freed.
 *
 * When `id` is not present, returns null and writes `0` into `*out_len`
 * without setting the last error.
 *
 * # Arguments
 *
 * * `ls`      — Localization set. Borrows.
 * * `kind`    — Which table to look in.
 * * `id`      — String entry ID.
 * * `out_len` — Written with the byte count on success, or `0` if not found.
 *
 * # Errors
 *
 * Returns null, writes `0` into `*out_len`, and sets the last error if
 * `ls` or `out_len` is null.
 */
const uint8_t *bethkit_localization_set_get(const struct BethkitLocalizationSet *ls,
                                            enum BethkitStringFileKind kind,
                                            uint32_t id,
                                            uintptr_t *out_len);

/**
 * Inserts or replaces string `id` of type `kind` in `ls`.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `ls`   — Localization set. Borrows.
 * * `kind` — Which table to write to.
 * * `id`   — Entry ID.
 * * `data` — Pointer to the byte payload. Borrows.
 * * `len`  — Number of bytes in `data`.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `ls` or `data` is null.
 */
int32_t bethkit_localization_set_set(struct BethkitLocalizationSet *ls,
                                     enum BethkitStringFileKind kind,
                                     uint32_t id,
                                     const uint8_t *data,
                                     uintptr_t len);

/**
 * Serializes all three string tables in `ls` to the file system using
 * Skyrim's sibling-file naming convention.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Arguments
 *
 * * `ls`          — Localization set. Borrows.
 * * `plugin_path` — NUL-terminated path to the `.esp`/`.esm` file. Borrows.
 * * `language`    — NUL-terminated language code. Borrows.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if any pointer is null, the paths
 * contain invalid UTF-8, or writing any file fails.
 */
int32_t bethkit_localization_set_write(const struct BethkitLocalizationSet *ls,
                                       const char *plugin_path,
                                       const char *language);

/**
 * Creates a new plugin writer for `game` at the given form version.
 *
 * Returns a pointer to the handle.  Must be freed with
 * [`bethkit_plugin_writer_free`].
 *
 * # Arguments
 *
 * * `game`         — Target game.
 * * `form_version` — Plugin form version (e.g. `44.0` for Skyrim SE).
 */
struct BethkitPluginWriter *bethkit_plugin_writer_new(enum BethkitGame game, float form_version);

/**
 * Frees a plugin writer handle.  Passing a null pointer is a no-op.
 */
void bethkit_plugin_writer_free(struct BethkitPluginWriter *pw);

/**
 * Appends a master filename to a borrowed plugin writer.
 *
 * Returns 0 on success. The filename is copied; neither pointer is consumed.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, invalid UTF-8, or panics.
 *
 * # Safety
 *
 * `pw` must be a live exclusively borrowed writer. `name` must point to a
 * readable NUL-terminated UTF-8 filename.
 */
int32_t bethkit_plugin_writer_add_master(struct BethkitPluginWriter *pw, const char *name);

/**
 * Replaces a borrowed plugin writer's description with a copied string.
 *
 * Returns 0 on success. Neither pointer is consumed.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for null pointers, invalid UTF-8, or panics.
 *
 * # Safety
 *
 * `pw` must be a live exclusively borrowed writer. `description` must point
 * to a readable NUL-terminated UTF-8 string.
 */
int32_t bethkit_plugin_writer_set_description(struct BethkitPluginWriter *pw,
                                              const char *description);

/**
 * Sets the localized-plugin header flag on a borrowed writer.
 *
 * Returns 0 on success. This does not convert record payloads or string tables.
 *
 * # Errors
 *
 * Returns -1 and sets the last error for a null writer or an internal panic.
 *
 * # Safety
 *
 * `pw` must be a live exclusively borrowed writer.
 */
int32_t bethkit_plugin_writer_set_localized(struct BethkitPluginWriter *pw, bool localized);

/**
 * Adds a top-level group to the plugin writer.
 *
 * This function **takes ownership** of `group`.  The caller must not use
 * or free `group` after this call.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `pw`    — Plugin writer. Borrows.
 * * `group` — Group to add. Ownership transferred.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `pw` or `group` is null.
 */
int32_t bethkit_plugin_writer_add_group(struct BethkitPluginWriter *pw,
                                        struct BethkitWritableGroup *group);

/**
 * Serializes the plugin to a file at `path`.
 *
 * Returns 0 on success or -1 on failure.
 *
 * # Arguments
 *
 * * `pw`   — Plugin writer. Borrows.
 * * `path` — NUL-terminated UTF-8 destination path. Borrows.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `pw` or `path` is null, the path
 * contains invalid UTF-8, or writing fails.
 */
int32_t bethkit_plugin_writer_write_to_file(const struct BethkitPluginWriter *pw, const char *path);

/**
 * Serializes the plugin to a heap-allocated byte buffer.
 *
 * On success, writes the buffer length into `*out_len` and returns a pointer
 * to the buffer.  The buffer must be freed with [`bethkit_bytes_free`].
 *
 * Returns null on failure and writes `0` into `*out_len`.
 *
 * # Arguments
 *
 * * `pw`      — Plugin writer. Borrows.
 * * `out_len` — Written with the buffer size on success, or `0` on failure.
 *
 * # Errors
 *
 * Returns null, writes `0` into `*out_len`, and sets the last error if
 * `pw` or `out_len` is null, or serialization fails.
 */
uint8_t *bethkit_plugin_writer_write_to_bytes(const struct BethkitPluginWriter *pw,
                                              uintptr_t *out_len);

/**
 * Creates a new writable group with the given 4-byte `label` and
 * `group_type`.
 *
 * Returns a pointer to the handle.  Ownership is transferred to the plugin
 * writer or parent group when this handle is added to one.
 *
 * # Arguments
 *
 * * `label`      — Pointer to 4 bytes used as the group label. Borrows.
 * * `group_type` — Bethesda group type integer.
 *
 * # Errors
 *
 * Returns null and sets the last error if `label` is null.
 */
struct BethkitWritableGroup *bethkit_writable_group_new(const uint8_t *label, int32_t group_type);

/**
 * Frees a writable group that was **not** added to a writer or parent group.
 *
 * Do not call this function after ownership has been transferred.  Passing a
 * null pointer is a no-op.
 */
void bethkit_writable_group_free(struct BethkitWritableGroup *group);

/**
 * Adds a record as a child of `group`.
 *
 * This function **takes ownership** of `record`.  The caller must not use
 * or free `record` after this call.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `group`  — Parent group. Borrows.
 * * `record` — Record to add. Ownership transferred.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `group` or `record` is null.
 */
int32_t bethkit_writable_group_add_record(struct BethkitWritableGroup *group,
                                          struct BethkitWritableRecord *record);

/**
 * Adds a child group inside `group`.
 *
 * This function **takes ownership** of `child`.  The caller must not use
 * or free `child` after this call.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `group` — Parent group. Borrows.
 * * `child` — Child group to add. Ownership transferred.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `group` or `child` is null.
 */
int32_t bethkit_writable_group_add_group(struct BethkitWritableGroup *group,
                                         struct BethkitWritableGroup *child);

/**
 * Creates a new writable record.
 *
 * Returns a pointer to the handle.  Ownership is transferred when the record
 * is added to a group.
 *
 * # Arguments
 *
 * * `signature`    — Pointer to 4 bytes for the record type signature. Borrows.
 * * `flags`        — Record flags word.
 * * `form_id`      — Raw FormID.
 * * `form_version` — Record form version.
 *
 * # Errors
 *
 * Returns null and sets the last error if `signature` is null.
 */
struct BethkitWritableRecord *bethkit_writable_record_new(const uint8_t *signature,
                                                          uint32_t flags,
                                                          uint32_t form_id,
                                                          uint16_t form_version);

/**
 * Frees a writable record that was **not** added to a group.
 *
 * Do not call this function after ownership has been transferred.  Passing a
 * null pointer is a no-op.
 */
void bethkit_writable_record_free(struct BethkitWritableRecord *record);

/**
 * Appends a sub-record to `record`.
 *
 * Returns 0 on success or -1 on error.
 *
 * # Arguments
 *
 * * `record`    — Record to append to. Borrows.
 * * `signature` — Pointer to 4 bytes for the sub-record type signature. Borrows.
 * * `data`      — Pointer to the raw sub-record payload bytes. Borrows.
 * * `data_len`  — Number of bytes in `data`.
 *
 * # Errors
 *
 * Returns -1 and sets the last error if `record`, `signature`, or `data` is
 * null.
 */
int32_t bethkit_writable_record_add_subrecord(struct BethkitWritableRecord *record,
                                              const uint8_t *signature,
                                              const uint8_t *data,
                                              uintptr_t data_len);

#endif  /* BETHKIT_H */
