[package]
name = "bethkit-schema"
version = "0.5.0"
edition = "2021"
build = "build.rs"

[features]
default = []
schema-skyrim-se = []

[dependencies]
bethkit-core = { path = "../bethkit-core" }
ciborium = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
